const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Timer,
		C3.Plugins.NinePatch,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Json,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.skymenTrail,
		C3.Behaviors.Sin,
		C3.Behaviors.Orbit,
		C3.Behaviors.skymen_RadialProgress,
		C3.Plugins.Particles,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.ScriptsInEvents.Gamesheet_Event3_Act1,
		C3.Plugins.TiledBg.Acts.SetImageOffsetX,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetLayerInteractive,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Particles.Acts.Destroy,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.ScriptsInEvents.Gamesheet_Event12_Act1,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Json.Exps.GetAsBeautifiedString,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.Spritefont2.Acts.SetSize,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Timer.Acts.PauseResumeTimer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.ScriptsInEvents.Gamesheet_Event54_Act1,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Spritefont2.Acts.SubInstanceVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Behaviors.skymen_RadialProgress.Acts.SetValue,
		C3.Behaviors.Timer.Exps.Duration,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Behaviors.Timer.Cnds.IsTimerPaused,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.skymenTrail.Acts.Attach,
		C3.Behaviors.skymenTrail.Acts.Reset,
		C3.Behaviors.skymenTrail.Acts.SetLength,
		C3.Plugins.System.Exps.fps,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Height,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.skymenTrail.Acts.SetWidthStart,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.TiledBg.Exps.BBoxTop,
		C3.Behaviors.Tween.Acts.SetTweensPlaybackRate,
		C3.Plugins.NinePatch.Exps.BBoxMidY,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Rotate.Acts.SetAcceleration,
		C3.Plugins.NinePatch.Exps.BBoxMidX,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Exps.Magnitude,
		C3.Plugins.Sprite.Exps.BBoxMidX,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Sin.Acts.UpdateInitialState,
		C3.Behaviors.Sin.Acts.SetPhase,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Acts.SetObjectTimescale,
		C3.ScriptsInEvents.Gamesheet_Event322_Act1,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Json.Exps.Front,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Json.Exps.Back,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Exps.ZIndex,
		C3.Plugins.NinePatch.Exps.ZIndex,
		C3.Behaviors.Sin.Acts.SetMovement,
		C3.Plugins.Json.Cnds.IsBooleanSet,
		C3.Behaviors.Orbit.Acts.SetEnabled,
		C3.Behaviors.Orbit.Acts.Pin,
		C3.Behaviors.Orbit.Acts.SetRadius,
		C3.Behaviors.Orbit.Acts.SetSpeed,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Spritefont2.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Spritefont2.Exps.Text,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.CurrentKey,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.TiledBg.Exps.ImageOffsetX,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.TiledBg.Exps.ImageScaleX,
		C3.Plugins.TiledBg.Exps.ImageWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Behaviors.Tween.Acts.SetTwoPropertiesTweensEndValue,
		C3.Plugins.NinePatch.Exps.Count,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.NinePatch.Acts.SetOpacity,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Loadersheet_Event2_Act2,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.NinePatch.Acts.SetVisible,
		C3.Plugins.System.Exps.max,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageOffsetY,
		C3.Plugins.TiledBg.Exps.ImageScaleY,
		C3.Plugins.TiledBg.Exps.ImageHeight,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Cnds.CompareHeight,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{StartW: 0},
	{StartH: 0},
	{Clickable: 0},
	{BtnClose: 0},
	{BtnDoonDookStudio: 0},
	{BtnMusic: 0},
	{BtnSFX: 0},
	{BtnInfo: 0},
	{BtnPlay: 0},
	{BtnHome: 0},
	{BtnNext: 0},
	{BtnPause: 0},
	{BtnReset: 0},
	{BtnResume: 0},
	{Reward: 0},
	{BtnWatchAd: 0},
	{BtnEndless: 0},
	{BtnReady: 0},
	{Tween: 0},
	{BtnStart: 0},
	{ScoredGoals: 0},
	{TxtBalls: 0},
	{TxtScore: 0},
	{TxtBallTimer: 0},
	{TxtGeneral: 0},
	{TxtGOTitle2: 0},
	{TxtGOTitle1: 0},
	{TxtLevelDone: 0},
	{TxtBtnLevel: 0},
	{TxtRv: 0},
	{TxtRv2: 0},
	{Num: 0},
	{Timer: 0},
	{TxtRvTimer: 0},
	{TxtLevel: 0},
	{TxtLevelDescription: 0},
	{TxtWind: 0},
	{InfoPopup: 0},
	{GameOverPopup: 0},
	{LvDonePopup: 0},
	{PausePopup: 0},
	{PopUpTitle: 0},
	{ChallengePopUp: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{JSON_Obstacles: 0},
	{JSON_Temp: 0},
	{JSON_LS: 0},
	{JSON_Config: 0},
	{Bg: 0},
	{BlackBg: 0},
	{IsShot: 0},
	{Force: 0},
	{MoveType: 0},
	{Angle_i: 0},
	{G: 0},
	{A_X: 0},
	{A_Z: 0},
	{V_Xi: 0},
	{V_Yi: 0},
	{V_Z: 0},
	{Xi: 0},
	{Yi: 0},
	{Zi: 0},
	{Yf: 0},
	{Finished: 0},
	{Rotate: 0},
	{Ball: 0},
	{BallShadow: 0},
	{TrailRenderer: 0},
	{BallTrail: 0},
	{BgGrass: 0},
	{Finger: 0},
	{HasLR: 0},
	{HasBS: 0},
	{HasObstacle: 0},
	{CurX: 0},
	{CurWidth: 0},
	{HasMoveX: 0},
	{HasChangeWidth: 0},
	{HasWind: 0},
	{HasMoveXVariance: 0},
	{HasChangeWidthVariance: 0},
	{HasLRVariance: 0},
	{HasBSVariance: 0},
	{HasWindVariance: 0},
	{IsCenterObstacle: 0},
	{Sine: 0},
	{GoalBottom: 0},
	{GoalBottomShadow: 0},
	{GoalCenter: 0},
	{Pos: 0},
	{GoalPost: 0},
	{GoalTop: 0},
	{GoalTopShadow: 0},
	{BallsBg: 0},
	{Type: 0},
	{Sine_Hor: 0},
	{Sine_Ver: 0},
	{Orbit: 0},
	{Obstacle: 0},
	{ScoreBg: 0},
	{RadialProgress: 0},
	{TimerProgress: 0},
	{Title: 0},
	{PatternBg: 0},
	{WindBg: 0},
	{WindDirection: 0},
	{BallsIcon: 0},
	{TimerBg: 0},
	{Sine2: 0},
	{Confetti: 0},
	{TryAgainBg: 0},
	{ConfettiParticles: 0},
	{Clouds: 0},
	{TopPanel: 0},
	{TransparentWindBg: 0},
	{LoadingBar: 0},
	{LoadingBg: 0},
	{LoadingFader: 0},
	{DDSLogo: 0},
	{FButtons: 0},
	{FPopup: 0},
	{Lives: 0},
	{Goals: 0},
	{Score: 0},
	{BestScore: 0},
	{GameSpeed: 0},
	{CloudSpeed: 0},
	{Difficulty: 0},
	{StartX: 0},
	{StartY: 0},
	{Turn: 0},
	{Wind: 0},
	{SeedNum: 0},
	{CanShoot: 0},
	{LevelMode: 0},
	{GoalPostWidth: 0},
	{StandardWidth: 0},
	{MinWidth: 0},
	{MaxWidth: 0},
	{MinX: 0},
	{MaxX: 0},
	{MinWind: 0},
	{MaxWind: 0},
	{vMoveX: 0},
	{vLR: 0},
	{vChangeWidth: 0},
	{vBS: 0},
	{vChangeWidth2: 0},
	{ID: 0},
	{EndX: 0},
	{EndY: 0},
	{vGoalLeft: 0},
	{vGoalRight: 0},
	{vWind: 0},
	{GoalPostID: 0},
	{BallID: 0},
	{ObstacleID: 0},
	{Enable: 0},
	{MinXChange: 0},
	{X_Left: 0},
	{X_Right: 0},
	{vX: 0},
	{CanChange: 0},
	{Width_Small: 0},
	{Width_Big: 0},
	{MinWidthChange: 0},
	{vWidth: 0},
	{PosX: 0},
	{Output: 0},
	{vMin: 0},
	{vMax: 0},
	{WidthDifference: 0},
	{JSON_Data: 0},
	{vLength: 0},
	{vIndex: 0},
	{vObstacleDifficulty: 0},
	{vRnd: 0},
	{OnlyCenter: 0},
	{Val: 0},
	{vLevel: 0},
	{InLevelDonePopup: 0},
	{Result: 0},
	{LS_KEY: 0},
	{ScreenWidth: 0},
	{ScreenHeight: 0},
	{MusicVol: 0},
	{ClickedButton: 0},
	{CurLayer: 0},
	{Which: 0},
	{Do: 0},
	{AfterClose: 0},
	{Name: 0},
	{Vol: 0}
];

self.InstanceType = {
	BtnClose: class extends self.ISpriteInstance {},
	BtnDoonDookStudio: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnResume: class extends self.ISpriteInstance {},
	BtnWatchAd: class extends self.ISpriteInstance {},
	BtnEndless: class extends self.ISpriteInstance {},
	BtnReady: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	TxtBalls: class extends self.ISpriteFontInstance {},
	TxtScore: class extends self.ISpriteFontInstance {},
	TxtBallTimer: class extends self.ISpriteFontInstance {},
	TxtGeneral: class extends self.ISpriteFontInstance {},
	TxtGOTitle2: class extends self.ISpriteFontInstance {},
	TxtGOTitle1: class extends self.ISpriteFontInstance {},
	TxtLevelDone: class extends self.ISpriteFontInstance {},
	TxtBtnLevel: class extends self.ISpriteFontInstance {},
	TxtRv: class extends self.ISpriteFontInstance {},
	TxtRv2: class extends self.ISpriteFontInstance {},
	TxtRvTimer: class extends self.ISpriteFontInstance {},
	TxtLevel: class extends self.ISpriteFontInstance {},
	TxtLevelDescription: class extends self.ISpriteFontInstance {},
	TxtWind: class extends self.ISpriteFontInstance {},
	InfoPopup: class extends self.IWorldInstance {},
	GameOverPopup: class extends self.IWorldInstance {},
	LvDonePopup: class extends self.IWorldInstance {},
	PausePopup: class extends self.IWorldInstance {},
	PopUpTitle: class extends self.IWorldInstance {},
	ChallengePopUp: class extends self.IWorldInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	JSON_Obstacles: class extends self.IJSONInstance {},
	JSON_Temp: class extends self.IJSONInstance {},
	JSON_LS: class extends self.IJSONInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	Bg: class extends self.ITiledBackgroundInstance {},
	BlackBg: class extends self.ITiledBackgroundInstance {},
	Ball: class extends self.ISpriteInstance {},
	BallShadow: class extends self.ISpriteInstance {},
	BallTrail: class extends self.ISpriteInstance {},
	BgGrass: class extends self.ITiledBackgroundInstance {},
	Finger: class extends self.ISpriteInstance {},
	GoalBottom: class extends self.ISpriteInstance {},
	GoalBottomShadow: class extends self.ISpriteInstance {},
	GoalCenter: class extends self.ISpriteInstance {},
	GoalPost: class extends self.ISpriteInstance {},
	GoalTop: class extends self.IWorldInstance {},
	GoalTopShadow: class extends self.IWorldInstance {},
	BallsBg: class extends self.ISpriteInstance {},
	Obstacle: class extends self.ISpriteInstance {},
	ScoreBg: class extends self.ISpriteInstance {},
	TimerProgress: class extends self.ISpriteInstance {},
	Title: class extends self.ISpriteInstance {},
	PatternBg: class extends self.ITiledBackgroundInstance {},
	WindBg: class extends self.ISpriteInstance {},
	WindDirection: class extends self.ISpriteInstance {},
	BallsIcon: class extends self.ISpriteInstance {},
	TimerBg: class extends self.ISpriteInstance {},
	Confetti: class extends self.ISpriteInstance {},
	TryAgainBg: class extends self.IWorldInstance {},
	ConfettiParticles: class extends self.IParticlesInstance {},
	Clouds: class extends self.ITiledBackgroundInstance {},
	TopPanel: class extends self.ITiledBackgroundInstance {},
	TransparentWindBg: class extends self.ITiledBackgroundInstance {},
	LoadingBar: class extends self.IWorldInstance {},
	LoadingBg: class extends self.ISpriteInstance {},
	LoadingFader: class extends self.ITiledBackgroundInstance {},
	DDSLogo: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FPopup: class extends self.IWorldInstance {}
}