const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.TiledBg,
		C3.Behaviors.Timer,
		C3.Behaviors.Tween,
		C3.Plugins.NinePatch,
		C3.Behaviors.Rotate,
		C3.Behaviors.MoveTo,
		C3.Plugins.Spritefont2,
		C3.Plugins.Json,
		C3.Plugins.Touch,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Arr,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Spritefont2.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemRemoved,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.Json.Acts.InsertValue,
		C3.Plugins.Json.Acts.SetJSON,
		C3.Plugins.Json.Exps.GetAsCompactString,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.Plugins.System.Acts.GoToLayout,
		C3.ScriptsInEvents.Loadersheet_Event11_Act1,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Exps.BBoxRight,
		C3.Plugins.Spritefont2.Exps.Width,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.TiledBg.Cnds.OnCreated,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.TiledBg.Exps.BBoxLeft,
		C3.Plugins.TiledBg.Exps.BBoxRight,
		C3.Plugins.Spritefont2.Cnds.OnCreated,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.TiledBg.Acts.SetImageScaleX,
		C3.Plugins.TiledBg.Acts.SetImageScaleY,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.SetWidth,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Cnds.IsOnLayer,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Exps.BBoxBottom,
		C3.Plugins.TiledBg.Cnds.CompareInstanceVar,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.canvastolayerx,
		C3.Plugins.System.Exps.layertocanvasx,
		C3.Plugins.System.Exps.layertocanvasy,
		C3.Plugins.System.Exps.canvastolayery,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Browser.Cnds.IsPortraitLandscape,
		C3.Plugins.System.Acts.SetLayerAngle,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.layerangle,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.TiledBg.Acts.SetAngle,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Exps.X,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Behaviors.Timer.Cnds.IsTimerRunning,
		C3.Behaviors.Timer.Acts.StopTimer,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Json.Cnds.CompareValue,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Plugins.NinePatch.Cnds.OnCreated,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.NinePatch.Acts.SetX,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Spritefont2.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.Spritefont2.Cnds.CompareText,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Json.Acts.AddTo,
		C3.Plugins.Json.Acts.SubtractFrom,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.NinePatch.Acts.SetY,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Behaviors.Timer.Acts.StopAllTimers,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Behaviors.Tween.Exps.Progress,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Timer.Exps.CurrentTime,
		C3.Plugins.Spritefont2.Exps.Count,
		C3.Plugins.Spritefont2.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Exps.Y,
		C3.Plugins.Spritefont2.Acts.ZMoveToObject,
		C3.Plugins.Spritefont2.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.NinePatch.Acts.SetHeight,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.Plugins.Sprite.Exps.LayerName,
		C3.Plugins.Spritefont2.Exps.BBoxRight,
		C3.Plugins.Sprite.Cnds.HasChildren,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.System.Exps.scrolly,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Touch.Exps.SpeedAt,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Behaviors.MoveTo.Exps.Speed,
		C3.Behaviors.MoveTo.Cnds.CompareSpeed,
		C3.Plugins.Json.Acts.RemoveValues,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.TiledBg.Acts.Destroy,
		C3.Plugins.Arr.Acts.Destroy,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.ScriptsInEvents.Gamesheet_Event56_Act1,
		C3.ScriptsInEvents.Gamesheet_Event58_Act1,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.NinePatch.Acts.ZMoveToObject,
		C3.Plugins.Sprite.Cnds.IsOnScreen,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.NinePatch.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Acts.RemoveChild,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.NinePatch.Acts.SetAngle,
		C3.Plugins.NinePatch.Cnds.AngleWithin,
		C3.Plugins.NinePatch.Cnds.CompareHeight,
		C3.Plugins.NinePatch.Cnds.CompareWidth,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.Spritefont2.Exps.X,
		C3.Plugins.Arr.Acts.SplitString,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Arr.Acts.SetInstanceVar,
		C3.Plugins.Arr.Cnds.CompareInstanceVar,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Exps.JoinString,
		C3.Plugins.System.Exps.replace,
		C3.Plugins.System.Cnds.ObjectUIDExists,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.System.Exps.left,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.TiledBg.Acts.SetImageOffsetY,
		C3.Plugins.TiledBg.Acts.ZMoveToObject,
		C3.ScriptsInEvents.Gamesheet_Event819_Act1,
		C3.Plugins.System.Acts.RestartLayout,
		C3.ScriptsInEvents.Gamesheet_Event824_Act1,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Sprite.Acts.MoveForward,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Spritefont2.Acts.SetScale,
		C3.Plugins.Spritefont2.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgbex255,
		C3.Plugins.System.Exps.choose,
		C3.Behaviors.Tween.Exps.Time,
		C3.Plugins.Spritefont2.Exps.BBoxBottom
	];
};
self.C3_JsPropNameTable = [
	{Arrow: 0},
	{Scale: 0},
	{Bg: 0},
	{Bg2: 0},
	{xx: 0},
	{yy: 0},
	{PathName: 0},
	{PathList: 0},
	{PathIDList: 0},
	{RoadsCount: 0},
	{Remains: 0},
	{PathNameLen: 0},
	{MoveStep: 0},
	{Moved: 0},
	{StartX: 0},
	{StartY: 0},
	{CurveX: 0},
	{CurveY: 0},
	{EndX: 0},
	{EndY: 0},
	{InitX: 0},
	{InitY: 0},
	{InitAngle: 0},
	{ObstaclesList: 0},
	{Clickable: 0},
	{initFrame: 0},
	{Index: 0},
	{IsOnHint: 0},
	{Hit: 0},
	{MovementPos: 0},
	{MovementFrame: 0},
	{Car: 0},
	{Pede: 0},
	{Crossing: 0},
	{Light: 0},
	{CarParent: 0},
	{Line: 0},
	{Dir: 0},
	{CrossingDir: 0},
	{Timer: 0},
	{Tween: 0},
	{Pedestrian: 0},
	{PedestrianOtherSide: 0},
	{PosFixer: 0},
	{Type: 0},
	{R: 0},
	{B: 0},
	{T: 0},
	{L: 0},
	{BL: 0},
	{BR: 0},
	{TL: 0},
	{TR: 0},
	{Possible: 0},
	{IsVisible: 0},
	{HasCar: 0},
	{Node: 0},
	{MultiLane: 0},
	{LaneTypes: 0},
	{G: 0},
	{Occupied: 0},
	{Phase2Overlap: 0},
	{CheckedP2: 0},
	{HasCrossing: 0},
	{HasTrafficLight: 0},
	{HasAdjacentPedestrian: 0},
	{HasEnd: 0},
	{MatchWithEnd: 0},
	{Road: 0},
	{State: 0},
	{initAngle: 0},
	{CrossDir: 0},
	{TrafficLight: 0},
	{LightShadow: 0},
	{MainW: 0},
	{MainH: 0},
	{BombEffect: 0},
	{ParevtUid: 0},
	{CarHitEffect: 0},
	{LanesNum: 0},
	{HasLine: 0},
	{EndRoad: 0},
	{InitW: 0},
	{InitH: 0},
	{HandTut: 0},
	{ParentUid: 0},
	{IsHintChecking: 0},
	{OverlappedCars: 0},
	{HintHelper: 0},
	{MidLine: 0},
	{CanCheck: 0},
	{MainY: 0},
	{RoadChecker: 0},
	{RoadEdgeLine: 0},
	{SelfY: 0},
	{TutCharacter: 0},
	{Mode: 0},
	{SelfW: 0},
	{SelfH: 0},
	{Rotate: 0},
	{TutStuff: 0},
	{UiPanel: 0},
	{PedeShadow: 0},
	{AvailableItemsParent: 0},
	{Item: 0},
	{ItemValue: 0},
	{BtnBuyShopItem: 0},
	{CollectionItemsParent: 0},
	{LockedItemsParent: 0},
	{SelectedItemFram: 0},
	{ShopHUDbg: 0},
	{ShopItemsPanel: 0},
	{ShopItemsPic: 0},
	{ShopPanel: 0},
	{CarPerview: 0},
	{SpeedReduceRate: 0},
	{MaxSpeed: 0},
	{CanSwipe: 0},
	{Swiping: 0},
	{CamY: 0},
	{MoveTo: 0},
	{Swiper: 0},
	{PicGarage: 0},
	{ShopBG: 0},
	{ShopTitlePanel: 0},
	{CoinShopItems: 0},
	{BlackBG: 0},
	{CoinIcon: 0},
	{CoinPanel: 0},
	{GameTitle: 0},
	{PopupPanel: 0},
	{PopupPic: 0},
	{BoosterCoinIcon: 0},
	{BoosterLable: 0},
	{Value: 0},
	{CoinPreview: 0},
	{WhiteBG: 0},
	{HomeBG: 0},
	{HomeBGStuff: 0},
	{HomeRoadBg: 0},
	{PanelBoosterTut: 0},
	{PopUp: 0},
	{PopupsLight: 0},
	{BtnBack: 0},
	{BtnClose: 0},
	{BtnDoonDook: 0},
	{Do: 0},
	{BtnNextLevel: 0},
	{BtnInfo: 0},
	{BtnMusic: 0},
	{BtnPlay: 0},
	{BtnSFX: 0},
	{BtnShop: 0},
	{BtnShopP: 0},
	{BtnWatchAd: 0},
	{BtnPause: 0},
	{BtnHome: 0},
	{BtnRetry: 0},
	{Price: 0},
	{BtnBombBooster: 0},
	{InvState: 0},
	{BtnHintBooster: 0},
	{BtnOk: 0},
	{type: 0},
	{TxtAdLable: 0},
	{TxtBuyShopItem: 0},
	{TxtCoin: 0},
	{TxtLevel: 0},
	{state: 0},
	{TxtPopupLabel: 0},
	{TxtMoves: 0},
	{TxtFloatMoves: 0},
	{TxtBoostersLabel: 0},
	{TxtTutDetail: 0},
	{TxtNECoinError: 0},
	{TxtTLTimer: 0},
	{TxtBoosterTut: 0},
	{TxtLoading: 0},
	{TxtInfo: 0},
	{PopupTitle: 0},
	{JSON_Config: 0},
	{JSON_LS: 0},
	{Touch: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{AJAX: 0},
	{Audio: 0},
	{ArrayCarFrames: 0},
	{ArrayCarPoss: 0},
	{TouchFixer: 0},
	{FCar: 0},
	{FLine: 0},
	{FRoad: 0},
	{FPedestrian: 0},
	{FEndRoad: 0},
	{FButton: 0},
	{FBoostersButton: 0},
	{FBtnBuyShopItem: 0},
	{FShopItemsPanel: 0},
	{FShopPanels: 0},
	{v: 0},
	{Moves: 0},
	{Ls_Key: 0},
	{CurLayer: 0},
	{ClickedButton: 0},
	{Level: 0},
	{IsWatchAd: 0},
	{GameOverState: 0},
	{ScreenHeight: 0},
	{ScreenWidth: 0},
	{LayoutMode: 0},
	{TempLayoutMode: 0},
	{ResLayoutMode: 0},
	{StartLayoutMode: 0},
	{LastLayer: 0},
	{LastCoinValue: 0},
	{AdTime: 0},
	{AdMode: 0},
	{Exeptional1: 0},
	{Exeptional2: 0},
	{Exeptional3: 0},
	{Exeptional4: 0},
	{Name: 0},
	{Volume: 0},
	{PType: 0},
	{PosX: 0},
	{PosY: 0},
	{LayerName: 0},
	{CreateNewItem: 0},
	{SelectedPanel: 0},
	{vMode: 0},
	{vLoopCounter: 0},
	{vColumn: 0},
	{vRow: 0},
	{vTSpeed: 0},
	{vY: 0},
	{Y: 0},
	{vCollWidth: 0},
	{BUid: 0},
	{BMode: 0},
	{MaxXX: 0},
	{MaxYY: 0},
	{TotalLanes: 0},
	{Part1: 0},
	{Part2: 0},
	{Part3: 0},
	{Part4: 0},
	{TotalRoads: 0},
	{MinPercent: 0},
	{MaxPercent: 0},
	{FirstRoad: 0},
	{GroupIndex: 0},
	{Phase2: 0},
	{Phase2Tries: 0},
	{Seed: 0},
	{Speed: 0},
	{TurnPercent: 0},
	{Spc: 0},
	{IsHitPedestrian: 0},
	{IsHitTrafficLight: 0},
	{CrashedCar: 0},
	{OnStart: 0},
	{IsOnBomb: 0},
	{CarCount: 0},
	{ComepleteGenerate: 0},
	{ComepletedCarCounter: 0},
	{ComepletedCars: 0},
	{IsFindFirstCar: 0},
	{CheckRoadsState: 0},
	{RecordPerSconde: 0},
	{vLevel: 0},
	{vMoves: 0},
	{vStartLM: 0},
	{vLastLayer: 0},
	{vCCars: 0},
	{vCompCarCount: 0},
	{vIndex: 0},
	{vLastIndex: 0},
	{vRes: 0},
	{vSeed: 0},
	{vMin: 0},
	{vMax: 0},
	{vList: 0},
	{vLeft: 0},
	{vRight: 0},
	{vTop: 0},
	{vBottom: 0},
	{vW: 0},
	{vH: 0},
	{vNeighbor: 0},
	{Uid: 0},
	{vRowIndex: 0},
	{CheckerUid: 0},
	{RowIndex: 0},
	{Checker: 0},
	{LineUid: 0},
	{RWidth: 0},
	{RHeight: 0},
	{RAngle: 0},
	{RLane: 0},
	{RoadID: 0},
	{vDist: 0},
	{Neighbor: 0},
	{vCount: 0},
	{vR: 0},
	{vRnd: 0},
	{vLanes: 0},
	{vNum: 0},
	{vTotalWeights: 0},
	{ID: 0},
	{Start: 0},
	{End: 0},
	{CarID: 0},
	{ArLayer: 0},
	{ForGameplay: 0},
	{vIsCrashedPede: 0},
	{vCurDir: 0},
	{vCurDirStart: 0},
	{vEndX: 0},
	{vEndY: 0},
	{vBetweenX: 0},
	{vBetweenY: 0},
	{vPos1X: 0},
	{vPos1Y: 0},
	{vPos2X: 0},
	{vPos2Y: 0},
	{vNextNum: 0},
	{vRUID: 0},
	{vVector: 0},
	{CUid: 0},
	{vPosX: 0},
	{vPosY: 0},
	{vFrame: 0},
	{Input: 0},
	{vCarPath: 0},
	{vStep1: 0},
	{vStep2: 0},
	{vDegree1: 0},
	{vDegree2: 0},
	{vNode1: 0},
	{vNode2: 0},
	{vRes2: 0},
	{vNode3: 0},
	{vType0: 0},
	{vG0: 0},
	{vMultiLane0: 0},
	{vPathEnd: 0},
	{vFirstCheck: 0},
	{vEndNode: 0},
	{ReturnEndNode: 0},
	{vDegree: 0},
	{vID: 0},
	{Step: 0},
	{Try: 0},
	{vPickedID: 0},
	{vAllDone: 0},
	{PerFrameAngle: 0},
	{FrameIndex: 0},
	{pAngle: 0},
	{vTimer: 0},
	{TrafficLightID: 0},
	{Degree: 0},
	{PedeUid: 0},
	{GOState: 0},
	{pRoadX: 0},
	{pRoadY: 0},
	{pCarAngle: 0},
	{pPathName: 0},
	{CarUid: 0},
	{vBoosterType: 0},
	{vInventory: 0},
	{vPrice: 0},
	{vSpace: 0},
	{TutType: 0}
];

self.InstanceType = {
	Arrow: class extends self.ISpriteInstance {},
	Bg: class extends self.ITiledBackgroundInstance {},
	Bg2: class extends self.ITiledBackgroundInstance {},
	Car: class extends self.ISpriteInstance {},
	Crossing: class extends self.ITiledBackgroundInstance {},
	Light: class extends self.ISpriteInstance {},
	Line: class extends self.ITiledBackgroundInstance {},
	Pedestrian: class extends self.ISpriteInstance {},
	PedestrianOtherSide: class extends self.ISpriteInstance {},
	PosFixer: class extends self.ISpriteInstance {},
	Road: class extends self.ISpriteInstance {},
	TrafficLight: class extends self.ISpriteInstance {},
	LightShadow: class extends self.ISpriteInstance {},
	BombEffect: class extends self.ISpriteInstance {},
	CarHitEffect: class extends self.ISpriteInstance {},
	EndRoad: class extends self.IWorldInstance {},
	HandTut: class extends self.ISpriteInstance {},
	HintHelper: class extends self.ISpriteInstance {},
	MidLine: class extends self.ITiledBackgroundInstance {},
	RoadChecker: class extends self.ISpriteInstance {},
	RoadEdgeLine: class extends self.IWorldInstance {},
	TutCharacter: class extends self.ISpriteInstance {},
	TutStuff: class extends self.ISpriteInstance {},
	UiPanel: class extends self.ISpriteInstance {},
	PedeShadow: class extends self.ISpriteInstance {},
	AvailableItemsParent: class extends self.ISpriteInstance {},
	BtnBuyShopItem: class extends self.ISpriteInstance {},
	CollectionItemsParent: class extends self.ISpriteInstance {},
	LockedItemsParent: class extends self.ISpriteInstance {},
	SelectedItemFram: class extends self.ISpriteInstance {},
	ShopHUDbg: class extends self.ITiledBackgroundInstance {},
	ShopItemsPanel: class extends self.ISpriteInstance {},
	ShopItemsPic: class extends self.ISpriteInstance {},
	ShopPanel: class extends self.IWorldInstance {},
	CarPerview: class extends self.ISpriteInstance {},
	Swiper: class extends self.ISpriteInstance {},
	PicGarage: class extends self.ISpriteInstance {},
	ShopBG: class extends self.ITiledBackgroundInstance {},
	ShopTitlePanel: class extends self.ISpriteInstance {},
	CoinShopItems: class extends self.ISpriteInstance {},
	BlackBG: class extends self.ITiledBackgroundInstance {},
	CoinIcon: class extends self.ISpriteInstance {},
	CoinPanel: class extends self.ISpriteInstance {},
	GameTitle: class extends self.ISpriteInstance {},
	PopupPanel: class extends self.ISpriteInstance {},
	PopupPic: class extends self.ISpriteInstance {},
	BoosterCoinIcon: class extends self.ISpriteInstance {},
	BoosterLable: class extends self.ISpriteInstance {},
	CoinPreview: class extends self.ISpriteInstance {},
	WhiteBG: class extends self.ITiledBackgroundInstance {},
	HomeBG: class extends self.ITiledBackgroundInstance {},
	HomeBGStuff: class extends self.ISpriteInstance {},
	HomeRoadBg: class extends self.ITiledBackgroundInstance {},
	PanelBoosterTut: class extends self.ISpriteInstance {},
	PopUp: class extends self.IWorldInstance {},
	PopupsLight: class extends self.ISpriteInstance {},
	BtnBack: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnDoonDook: class extends self.ISpriteInstance {},
	BtnNextLevel: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnShop: class extends self.ISpriteInstance {},
	BtnShopP: class extends self.ISpriteInstance {},
	BtnWatchAd: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnRetry: class extends self.ISpriteInstance {},
	BtnBombBooster: class extends self.ISpriteInstance {},
	BtnHintBooster: class extends self.ISpriteInstance {},
	BtnOk: class extends self.ISpriteInstance {},
	TxtAdLable: class extends self.ISpriteFontInstance {},
	TxtBuyShopItem: class extends self.ISpriteFontInstance {},
	TxtCoin: class extends self.ISpriteFontInstance {},
	TxtLevel: class extends self.ISpriteFontInstance {},
	TxtPopupLabel: class extends self.ISpriteFontInstance {},
	TxtMoves: class extends self.ISpriteFontInstance {},
	TxtFloatMoves: class extends self.ISpriteFontInstance {},
	TxtBoostersLabel: class extends self.ISpriteFontInstance {},
	TxtTutDetail: class extends self.ISpriteFontInstance {},
	TxtNECoinError: class extends self.ISpriteFontInstance {},
	TxtTLTimer: class extends self.ISpriteFontInstance {},
	TxtBoosterTut: class extends self.ISpriteFontInstance {},
	TxtLoading: class extends self.ISpriteFontInstance {},
	TxtInfo: class extends self.ISpriteFontInstance {},
	PopupTitle: class extends self.ISpriteFontInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	JSON_LS: class extends self.IJSONInstance {},
	Touch: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	ArrayCarFrames: class extends self.IArrayInstance {},
	ArrayCarPoss: class extends self.IArrayInstance {},
	TouchFixer: class extends self.ISpriteInstance {},
	FCar: class extends self.ISpriteInstance {},
	FLine: class extends self.ITiledBackgroundInstance {},
	FRoad: class extends self.ISpriteInstance {},
	FPedestrian: class extends self.ISpriteInstance {},
	FEndRoad: class extends self.IWorldInstance {},
	FButton: class extends self.ISpriteInstance {},
	FBoostersButton: class extends self.ISpriteInstance {},
	FBtnBuyShopItem: class extends self.ISpriteInstance {},
	FShopItemsPanel: class extends self.ISpriteInstance {},
	FShopPanels: class extends self.IWorldInstance {}
}