const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Plugins.Text,
		C3.Behaviors.Timer,
		C3.Plugins.NinePatch,
		C3.Plugins.AJAX,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.LocalStorage,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Json,
		C3.Plugins.TiledBg,
		C3.Behaviors.Tween,
		C3.Behaviors.Sin,
		C3.Behaviors.Bullet,
		C3.Behaviors.Rotate,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.IsPreview,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.NinePatch.Acts.Destroy,
		C3.Plugins.Touch.Cnds.OnNthTouchEnd,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Audio.Acts.FadeVolume,
		C3.Plugins.TiledBg.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.TiledBg.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Cnds.IsOnLayer,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Text.Cnds.IsOnLayer,
		C3.Plugins.Text.Acts.SetPos,
		C3.ScriptsInEvents.Gamesheet_Event45_Act1,
		C3.Plugins.Json.Acts.SetArray,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Acts.RestartLayout,
		C3.ScriptsInEvents.Gamesheet_Event47_Act1,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToCompactString,
		C3.ScriptsInEvents.Gamesheet_Event51_Act1,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Exps.tokencount,
		C3.Plugins.System.Exps.find,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.NinePatch.Acts.SetInstanceVar,
		C3.Plugins.NinePatch.Exps.BBoxLeft,
		C3.Plugins.NinePatch.Exps.BBoxRight,
		C3.Plugins.NinePatch.Cnds.CompareInstanceVar,
		C3.Plugins.NinePatch.Exps.PickedCount,
		C3.Plugins.NinePatch.Exps.BBoxTop,
		C3.Plugins.NinePatch.Exps.BBoxBottom,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Cnds.PickByHighestLowestValue,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.TiledBg.Acts.AddChild,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.NinePatch.Acts.AddChild,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.NinePatch.Exps.IID,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.AddInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.tokenat,
		C3.Plugins.Sprite.Exps.PickedCount,
		C3.Plugins.System.Cnds.PickNth,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Cnds.PickInstVarHiLow,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Exps.BBoxBottom,
		C3.ScriptsInEvents.Gamesheet_Event139_Act1,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Behaviors.Tween.Cnds.IsAnyPlaying,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Exps.BBoxTop,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.Count,
		C3.Behaviors.Tween.Cnds.OnTweensFinished,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.NinePatch.Cnds.PickInstVarHiLow,
		C3.Plugins.NinePatch.Exps.UID,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.NinePatch.Exps.X,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.NinePatch.Cnds.PickChildren,
		C3.Plugins.NinePatch.Cnds.PickByUID,
		C3.Plugins.NinePatch.Exps.Y,
		C3.Plugins.NinePatch.Exps.Width,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Json.Cnds.HasKey,
		C3.Plugins.Json.Acts.PushValue,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Acts.PopValue,
		C3.Behaviors.Tween.Acts.StopAllTweens,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Text.Cnds.CompareInstanceVar,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Exps.ImageWidth,
		C3.Plugins.Sprite.Exps.ImageHeight,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Behaviors.Bullet.Acts.SetGravity,
		C3.Behaviors.Bullet.Exps.Speed,
		C3.Behaviors.Rotate.Acts.SetSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Behaviors.Rotate.Acts.SetEnabled,
		C3.Behaviors.Bullet.Cnds.IsEnabled,
		C3.Behaviors.Tween.Cnds.IsPlaying,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.ScriptsInEvents.Loadersheet_Event2_Act1,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Browser.Acts.GoToURLWindow,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.NinePatch.Exps.LayerName,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.NinePatch.Cnds.IsOnLayer,
		C3.Behaviors.Tween.Acts.TweenValue,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Behaviors.Tween.Exps.Value,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Audio.Acts.Stop
	];
};
self.C3_JsPropNameTable = [
	{StartW: 0},
	{StartH: 0},
	{Clickable: 0},
	{BtnUndo: 0},
	{BtnClose: 0},
	{BtnDoonDookStudio: 0},
	{BtnInfo: 0},
	{BtnMusic: 0},
	{BtnPlay: 0},
	{BtnSFX: 0},
	{Reward: 0},
	{BtnWatchAd: 0},
	{BtnPause: 0},
	{BtnResume: 0},
	{BtnHome: 0},
	{BtnReset: 0},
	{BtnNext: 0},
	{BtnOK: 0},
	{BtnAddTube: 0},
	{TxtInfo: 0},
	{TxtBtnPlay: 0},
	{TxtLoading: 0},
	{TxtUndoCount: 0},
	{TxtBuyBooster: 0},
	{TxtRv: 0},
	{Num: 0},
	{Timer: 0},
	{TxtRvTimer: 0},
	{TxtRv2: 0},
	{TxtLevel: 0},
	{TxtLabel: 0},
	{BuyBoosterPopup: 0},
	{LvDonePopup: 0},
	{PausePopup: 0},
	{LosePopup: 0},
	{AJAX: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{LocalStorage: 0},
	{Mouse: 0},
	{Touch: 0},
	{JSON_Config: 0},
	{JSON_LS: 0},
	{JSON_Undo: 0},
	{Tween: 0},
	{BlackBg: 0},
	{BoardFixer: 0},
	{UndoCountBg: 0},
	{BoosterIcon: 0},
	{Box: 0},
	{InfoPopup: 0},
	{Title: 0},
	{Step: 0},
	{PosList: 0},
	{Sine: 0},
	{Hand: 0},
	{Index: 0},
	{Parent: 0},
	{TargetY: 0},
	{From: 0},
	{To: 0},
	{Ball: 0},
	{Speed: 0},
	{Scale: 0},
	{Bullet: 0},
	{Rotate: 0},
	{ParticlesConfetti: 0},
	{RowFixer: 0},
	{xx: 0},
	{yy: 0},
	{Spot: 0},
	{Sprite: 0},
	{TiledBackground: 0},
	{BallsCount: 0},
	{Done: 0},
	{Tube: 0},
	{TubeConfetti: 0},
	{TubeTop: 0},
	{FButtons: 0},
	{FPopup: 0},
	{FSpot: 0},
	{FBall: 0},
	{FTube: 0},
	{Level: 0},
	{Seed: 0},
	{TubesCount: 0},
	{SidesSpc: 0},
	{TubesHeight: 0},
	{SpcY: 0},
	{StepsCount: 0},
	{FirstTube: 0},
	{SecondTube: 0},
	{AdReward: 0},
	{TutStep: 0},
	{ColorsList: 0},
	{vTop: 0},
	{InLevelDonePopup: 0},
	{vRnd: 0},
	{vCreatedCount: 0},
	{vL: 0},
	{vR: 0},
	{vCount: 0},
	{vMaxInRow: 0},
	{vY: 0},
	{vBottom: 0},
	{vCount1: 0},
	{vCount2: 0},
	{TubeID: 0},
	{vIndex: 0},
	{vRes: 0},
	{vSeed: 0},
	{vLevel: 0},
	{vType: 0},
	{vMin: 0},
	{vMax: 0},
	{vFrame: 0},
	{vDone: 0},
	{WithEffects: 0},
	{SpotID: 0},
	{vTubeIndex: 0},
	{vUID: 0},
	{vSpd: 0},
	{vAng: 0},
	{Ang: 0},
	{vPrtcSpeedRight: 0},
	{vPrtcSpeedLeft: 0},
	{vPrtcAngleRight: 0},
	{vPrtcAngleLeft: 0},
	{Dir: 0},
	{vFound: 0},
	{BallID: 0},
	{TargetTubeID: 0},
	{LSKey: 0},
	{ConfigLoaded: 0},
	{LSLoaded: 0},
	{ScriptsLoaded: 0},
	{ScreenWidth: 0},
	{ScreenHeight: 0},
	{MusicVol: 0},
	{ClickedButton: 0},
	{CurLayer: 0},
	{Which: 0},
	{Do: 0},
	{AfterClose: 0},
	{Name: 0}
];

self.InstanceType = {
	BtnUndo: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	BtnDoonDookStudio: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnSFX: class extends self.ISpriteInstance {},
	BtnWatchAd: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnResume: class extends self.ISpriteInstance {},
	BtnHome: class extends self.ISpriteInstance {},
	BtnReset: class extends self.ISpriteInstance {},
	BtnNext: class extends self.ISpriteInstance {},
	BtnOK: class extends self.ISpriteInstance {},
	BtnAddTube: class extends self.ISpriteInstance {},
	TxtInfo: class extends self.ITextInstance {},
	TxtBtnPlay: class extends self.ITextInstance {},
	TxtLoading: class extends self.ITextInstance {},
	TxtUndoCount: class extends self.ITextInstance {},
	TxtBuyBooster: class extends self.ITextInstance {},
	TxtRv: class extends self.ITextInstance {},
	TxtRvTimer: class extends self.ITextInstance {},
	TxtRv2: class extends self.ITextInstance {},
	TxtLevel: class extends self.ITextInstance {},
	TxtLabel: class extends self.ITextInstance {},
	BuyBoosterPopup: class extends self.IWorldInstance {},
	LvDonePopup: class extends self.IWorldInstance {},
	PausePopup: class extends self.IWorldInstance {},
	LosePopup: class extends self.IWorldInstance {},
	AJAX: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	JSON_LS: class extends self.IJSONInstance {},
	JSON_Undo: class extends self.IJSONInstance {},
	BlackBg: class extends self.ITiledBackgroundInstance {},
	BoardFixer: class extends self.ITiledBackgroundInstance {},
	UndoCountBg: class extends self.ISpriteInstance {},
	BoosterIcon: class extends self.ISpriteInstance {},
	Box: class extends self.IWorldInstance {},
	InfoPopup: class extends self.IWorldInstance {},
	Title: class extends self.ISpriteInstance {},
	Hand: class extends self.ISpriteInstance {},
	Ball: class extends self.ISpriteInstance {},
	ParticlesConfetti: class extends self.ISpriteInstance {},
	RowFixer: class extends self.ISpriteInstance {},
	Spot: class extends self.IWorldInstance {},
	Sprite: class extends self.ISpriteInstance {},
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Tube: class extends self.ISpriteInstance {},
	TubeConfetti: class extends self.ISpriteInstance {},
	TubeTop: class extends self.ISpriteInstance {},
	FButtons: class extends self.ISpriteInstance {},
	FPopup: class extends self.IWorldInstance {},
	FSpot: class extends self.IWorldInstance {},
	FBall: class extends self.ISpriteInstance {},
	FTube: class extends self.ISpriteInstance {}
}